baseURL = 'https://blue-beach-035c95a00.2.azurestaticapps.net/'
languageCode = 'en-us'
title = 'CakraVal :: Cakrawala Val Teknologi'
theme = 'hugo-universal-theme'

[params]
    disabled_logo = false
    logo_text = ".:: CakraVal ::."

    logo = "/../img/cval-hugo-universal-logo.png"
    logo_small = "/../img/cval-hugo-universal-logo-small.png"

    dropdown_mouse_over = true

    address = """<p class="text-uppercase"><strong>PT Cakrawala Val Teknologi</strong>
        <br>CHR Office  Grand Slipi Tower Lt. 9 Unit O
        <br>Jl. Letjend. S. Parman, Kav 22-24 RT 001 RW 004 Palmerah
        <br>Jakarta Barat 11480 
        <br>DKI Jakarta
        <br>
        <br> +62-21-39720660
        <br> hello@cakraval.com
        <br>
        <br>
        <strong>Indonesia</strong>
      </p>
      """
    about_us = """<p>CakraVal is an IT service company based in Jakarta.
        <br>
        <br>. We strive to offer the best service for all topics related to IT. Our goal is to provide a complete set of IT services, so we offer our Clients a complete takeover of their existing infrastructure, including server management, desktop management, and network management. We solve all our Client problems on all possible levels, so our clients don't have to worry about anything and focus on their core business and not constantly worry about their IT infrastructure.
        <br>
        </p>CakraVal is specializing in helping out small and medium-sized businesses. However, we also work for large corporations on a contract basis. We strive to bring the best services to the Clients: consulting, system implementation or migration, knowledge transfer, IT processes or system assessment/audit, and professional outsourcing.
        <br>
        </p>We would like to emphasize a good partnership to each Client so they will know the benefit of what they will decide and bring our services to their organization.
        <br>
        </p>Founded in 2020 by a practitioner with years-of-experience at  IT operation and management in many industries, its vision is to help Clients running the IT transformation, tailor the system by considering the process, people, and technology..
        <br>
        </p>Our collaborations will form the Clients’ mindset of ‘IT’s easy!’. It means no worry about IT and they will be ready to shift the focus to core business. 
        """
    copyright = "Copyright (c) 2022, PT Cakrawala Val Teknologi; all rights reserved."

[params.topbar]
    enable = true
    text = "<p>Contact us on +62 21 397 20660 or hello@cakraval.com</p>"

    contact_url = "/contact"


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "https://wa.me/622139720660"
    pre = "<i class='fab fa-2x fa-whatsapp'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/baguswinarko"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"





# Main menu

[[menu.main]]
    name       = "About"
    identifier = "menu.portfolio"
    url        = "/img/template-homepage.png"
    weight     = 3

[[menu.main]]
    name       = "Portfolio"
    identifier = "section.portfolio"
    url        = ""
    weight     = 1
    parent     = "menu.portfolio"
    post       = 1

[[menu.main]]
    name       = "2 Columns"
    url        = ""
    weight     = 1
    parent     = "section.portfolio"

[[menu.main]]
    name       = "2 Columns With Negative Space"
    url        = ""
    weight     = 2
    parent     = "section.portfolio"

[[menu.main]]
    name       = "3 Columns"
    url        = ""
    weight     = 3
    parent     = "section.portfolio"

[[menu.main]]
    name       = "3 Columns With Negative Space"
    url        = ""
    weight     = 4
    parent     = "section.portfolio"

[[menu.main]]
    name       = "4 Columns"
    url        = ""
    weight     = 5
    parent     = "section.portfolio"

[[menu.main]]
    name       = "4 Columns With Negative Space"
    url        = ""
    weight     = 6
    parent     = "section.portfolio"

[[menu.main]]
    name       = "Portfolio - detail"
    url        = ""
    weight     = 7
    parent     = "section.portfolio"

[[menu.main]]
    name       = "Portfolio - detail 2"
    url        = ""
    weight     = 8
    parent     = "section.portfolio"

[[menu.main]]
    name       = "About"
    identifier = "section.about"
    url        = ""
    weight     = 2
    parent     = "menu.portfolio"
    post       = 2

[[menu.main]]
    name       = "About Us"
    url        = ""
    weight     = 1
    parent     = "section.about"

[[menu.main]]
    name       = "Our Team"
    url        = ""
    weight     = 2
    parent     = "section.about"

[[menu.main]]
    name       = "Marketing"
    identifier = "section.marketing"
    url        = ""
    weight     = 3
    parent     = "menu.portfolio"
    post       = 2

[[menu.main]]
    name       = "Packages"
    url        = ""
    weight     = 1
    parent     = "section.marketing"

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5

[[menu.main]]
    name       = "FAQ"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7



# Enable and disable widgets for the right sidebar
[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.