baseURL = 'https://blue-beach-035c95a00.2.azurestaticapps.net/'
languageCode = 'en-us'
title = 'CakraVal :: Cakrawala Val Teknology'
theme = 'hugo-universal-theme'

[params]
    disabled_logo = false
    logo_text = "Universal"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

[[params.menu]]
    name = "Contact"
    url  = "/contact"
    weight = 4    

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1