baseURL = 'https://blue-beach-035c95a00.2.azurestaticapps.net/'
languageCode = 'en-us'
title = 'CakraVal :: Cakrawala Val Teknology'
theme = 'hugo-universal-theme'

[params]
    disabled_logo = false
    logo_text = "Universal"

    logo = "/../img/cval-hugo-universal-logo.png"
    logo_small = "img/logo-small.png"

[params.topbar]
    enable = true
    text = "<p>Contact us on +62 21 397 20660 or hello@cakraval.com</p>"


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+62 21 397 20660"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/baguswinarko"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"





[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1